project_id = "mfjllillnpleasclqabb"

[global.config]
runtime = "deno"

[[global.functions]]
name = "ai-chat"
verify_jwt = true

[[global.functions]]
name = "ai-job-assistant"
verify_jwt = true

[[global.functions]]
name = "fetch-jobs"
verify_jwt = true

[[global.functions]]
name = "get-secret"
verify_jwt = true

[[global.functions]]
name = "ai-agents"
verify_jwt = true

[[global.functions]]
name = "create-profile"
verify_jwt = true