import { Json } from './auth';

export interface JobTypes {
  Tables: {
    jobs: {
      Row: {
        id: string;
        title: string;
        description: string;
        budget: number;
        location: string;
        employer_id: string;
        status: string;
        created_at: string | null;
        updated_at: string | null;
        category: string;
        contract_type: string;
        experience_level: string;
        subcategory: string | null;
        latitude: number | null;
        longitude: number | null;
        images: string[] | null;
        required_skills: string[] | null;
        preferred_skills: string[] | null;
        remote_type: string | null;
        application_deadline: string | null;
        company_name: string | null;
        company_logo: string | null;
        company_website: string | null;
        company_description: string | null;
        salary_min: number | null;
        salary_max: number | null;
        salary_currency: string | null;
        salary_period: string | null;
        benefits: string[] | null;
        responsibilities: string[] | null;
        qualifications: string[] | null;
        job_type: string | null;
        work_schedule: string[] | null;
        languages: string[] | null;
        certifications_required: string[] | null;
        tools_and_technologies: string[] | null;
        industry: string | null;
        department: string | null;
        education_level: string | null;
        years_of_experience: number | null;
        mission_type: string;
        payment_schedule: string | null;
        is_urgent: boolean | null;
      };
      Insert: {
        title: string;
        description: string;
        budget: number;
        location: string;
        employer_id: string;
        status?: string;
        created_at?: string | null;
        updated_at?: string | null;
        category: string;
        contract_type: string;
        experience_level: string;
        subcategory?: string | null;
        latitude?: number | null;
        longitude?: number | null;
        images?: string[] | null;
        required_skills?: string[] | null;
        preferred_skills?: string[] | null;
        remote_type?: string | null;
        application_deadline?: string | null;
        company_name?: string | null;
        company_logo?: string | null;
        company_website?: string | null;
        company_description?: string | null;
        salary_min?: number | null;
        salary_max?: number | null;
        salary_currency?: string | null;
        salary_period?: string | null;
        benefits?: string[] | null;
        responsibilities?: string[] | null;
        qualifications?: string[] | null;
        job_type?: string | null;
        work_schedule?: string[] | null;
        languages?: string[] | null;
        certifications_required?: string[] | null;
        tools_and_technologies?: string[] | null;
        industry?: string | null;
        department?: string | null;
        education_level?: string | null;
        years_of_experience?: number | null;
        mission_type: string;
        payment_schedule?: string | null;
        is_urgent?: boolean | null;
      };
      Update: {
        id: string;
        title?: string;
        description?: string;
        budget?: number;
        location?: string;
        employer_id?: string;
        status?: string;
        created_at?: string | null;
        updated_at?: string | null;
        category?: string;
        contract_type?: string;
        experience_level?: string;
        subcategory?: string | null;
        latitude?: number | null;
        longitude?: number | null;
        images?: string[] | null;
        required_skills?: string[] | null;
        preferred_skills?: string[] | null;
        remote_type?: string | null;
        application_deadline?: string | null;
        company_name?: string | null;
        company_logo?: string | null;
        company_website?: string | null;
        company_description?: string | null;
        salary_min?: number | null;
        salary_max?: number | null;
        salary_currency?: string | null;
        salary_period?: string | null;
        benefits?: string[] | null;
        responsibilities?: string[] | null;
        qualifications?: string[] | null;
        job_type?: string | null;
        work_schedule?: string[] | null;
        languages?: string[] | null;
        certifications_required?: string[] | null;
        tools_and_technologies?: string[] | null;
        industry?: string | null;
        department?: string | null;
        education_level?: string | null;
        years_of_experience?: number | null;
        mission_type?: string;
        payment_schedule?: string | null;
        is_urgent?: boolean | null;
      };
    };
    job_categories: {
      Row: {
        id: string;
        name: string;
        mission_type: string;
        created_at: string | null;
      };
      Insert: {
        name: string;
        mission_type: string;
        created_at?: string | null;
      };
      Update: {
        id: string;
        name?: string;
        mission_type?: string;
        created_at?: string | null;
      };
    };
    job_subcategories: {
      Row: {
        id: string;
        category_id: string | null;
        name: string;
        created_at: string | null;
      };
      Insert: {
        category_id?: string | null;
        name: string;
        created_at?: string | null;
      };
      Update: {
        id: string;
        category_id?: string | null;
        name?: string;
        created_at?: string | null;
      };
    };
  };
}
