
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { corsHeaders } from '../_shared/cors.ts';

const TIMEOUT_DURATION = 25000;
const OPENROUTER_API_KEY = Deno.env.get('OPENROUTER_API_KEY');

interface Message {
  role: "system" | "user" | "assistant";
  content: string;
}

interface RequestBody {
  messages: Message[];
  userId?: string;
  userProfile?: {
    full_name?: string;
  };
}

console.log("Starting victaure-chat function with OpenRouter");

if (!OPENROUTER_API_KEY) {
  console.error("OPENROUTER_API_KEY is not set");
  throw new Error("OPENROUTER_API_KEY is not set");
}

async function fetchWithTimeout(promise: Promise<any>, timeout: number) {
  let timeoutId: number;
  
  const timeoutPromise = new Promise((_, reject) => {
    timeoutId = setTimeout(() => {
      reject(new Error(`Operation timed out after ${timeout}ms`));
    }, timeout);
  });

  try {
    const result = await Promise.race([promise, timeoutPromise]);
    clearTimeout(timeoutId);
    return result;
  } catch (error) {
    clearTimeout(timeoutId);
    throw error;
  }
}

serve(async (req) => {
  console.log(`[${new Date().toISOString()}] Request received:`, req.method);

  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { messages, userId, userProfile } = await req.json() as RequestBody;
    console.log(`[${new Date().toISOString()}] Processing request for ${userProfile?.full_name || 'anonymous'}`);

    if (!messages?.length) {
      throw new Error("Messages array is required and must not be empty");
    }

    // Contexte système amélioré pour Mr Victaure
    const systemContext = `Tu es Mr Victaure, un assistant professionnel hautement qualifié spécialisé dans le conseil en carrière et le recrutement. 

Ton profil :
- Tu as plus de 15 ans d'expérience dans le recrutement et le développement de carrière au Canada
- Tu es diplômé en psychologie organisationnelle et en ressources humaines
- Tu maîtrises parfaitement le français et les subtilités de la communication professionnelle
- Tu es expert dans l'analyse des compétences et du potentiel professionnel

Directives de comportement :
- Reste toujours professionnel et bienveillant
- Vérifie soigneusement ta grammaire et ton orthographe
- Fournis des réponses précises et factuelles basées sur ton expertise
- Pose des questions pertinentes pour mieux comprendre les besoins
- Adapte ton niveau de langage au contexte tout en restant professionnel
- Si tu ne connais pas quelque chose avec certitude, admets-le honnêtement

${userId ? `Tu parles actuellement à ${userProfile?.full_name}.` : 'Tu parles à un visiteur.'} 

Concentre-toi sur :
- L'aide à la recherche d'emploi
- Le développement de carrière
- Les conseils en entretien
- L'analyse du marché du travail
- L'orientation professionnelle
- Les tendances de l'emploi au Canada

Évite :
- Les réponses vagues ou génériques
- Les plaisanteries inappropriées
- Les conseils non fondés
- Les sujets hors de ton domaine d'expertise`;

    // Utilise le modèle plus puissant gpt-4o
    const openRouterPromise = fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'HTTP-Referer': 'https://victaure.com',
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: "gpt-4o",
        messages: [
          { role: "system", content: systemContext },
          ...messages.slice(1)  // Exclure l'ancien contexte système
        ],
        temperature: 0.7,
        max_tokens: 1000,
        frequency_penalty: 0.5,
        presence_penalty: 0.5
      })
    });

    const response = await fetchWithTimeout(openRouterPromise, TIMEOUT_DURATION);
    const data = await response.json();

    console.log(`[${new Date().toISOString()}] OpenRouter API responded successfully`);

    if (!data.choices?.length) {
      throw new Error("No response generated by OpenRouter");
    }

    return new Response(
      JSON.stringify({ choices: data.choices }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error) {
    console.error(`[${new Date().toISOString()}] Error:`, error);

    const errorResponse = {
      error: {
        message: error instanceof Error ? error.message : "An unknown error occurred",
        name: error instanceof Error ? error.name : "UnknownError",
        timestamp: new Date().toISOString()
      }
    };

    return new Response(
      JSON.stringify(errorResponse),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});
