import { z } from "zod";

export const jobFormSchema = z.object({
  title: z.string().min(1, "Le titre est requis"),
  description: z.string().min(1, "La description est requise"),
  budget: z.string().transform((val) => Number(val)),
  location: z.string().min(1, "La localisation est requise"),
  category: z.string().min(1, "La catégorie est requise"),
  subcategory: z.string().optional(),
  mission_type: z.enum(["company", "individual"]).default("company"),
  contract_type: z.string().min(1, "Le type de contrat est requis"),
  experience_level: z.string().optional(),
  remote_type: z.string().min(1, "Le type de travail est requis"),
  payment_schedule: z.string().min(1, "Le type de paiement est requis"),
  is_urgent: z.boolean().default(false),
  required_skills: z.array(z.string()).optional(),
  preferred_skills: z.array(z.string()).optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  company_name: z.string().optional(),
  company_logo: z.string().optional(),
  company_website: z.string().optional(),
  company_description: z.string().optional(),
  salary_min: z.number().min(0, "Le salaire minimum doit être positif"),
  salary_max: z.number().min(0, "Le salaire maximum doit être positif"),
  salary_currency: z.string().default("CAD"),
  salary_period: z.string().default("yearly"),
  benefits: z.array(z.string()).optional(),
  responsibilities: z.array(z.string()).optional(),
  qualifications: z.array(z.string()).optional(),
});

export type JobFormValues = z.infer<typeof jobFormSchema>;

export const defaultValues: JobFormValues = {
  title: "",
  description: "",
  budget: 0,
  location: "",
  category: "Technology",
  subcategory: "",
  mission_type: "company",
  contract_type: "Full-time",
  experience_level: "Mid-Level",
  remote_type: "on-site",
  required_skills: [],
  preferred_skills: [],
  salary_currency: "CAD",
  salary_period: "yearly",
  benefits: [],
  responsibilities: [],
  qualifications: [],
  is_urgent: false,
  payment_schedule: "Monthly",
  salary_min: 0,
  salary_max: 0,
  company_name: "",
  company_logo: "",
  company_website: "",
  company_description: "",
  latitude: 0,
  longitude: 0,
};